version: '3.8'
services:
    rstudio:
        build:
            context: .
        environment:
            - TZ=Asia/Tokyo
            - DISABLE_AUTH=true
            - RENV_PATHS_CACHE=/home/rstudio/.renv/cache
        volumes:
            # If you want to use renv cache from your host machine, uncomment and modify the following line
            - ~/Library/Caches/org.R-project.R/R/renv/cache:/home/rstudio/.renv/cache
            - .:/home/rstudio
        ports:
            - 8787:8787