# appid <- "12604ebf628834b46b3867721893644141fe9a34"
library(dplyr) 
library(tidyr) 
library(ggplot2)
library(gt)
library(gtExtras)
library(purrr)
library(readr)
library(stringr)
library(stringi)
library(here)
library(openxlsx)
library(readxl)
library(httpgd)
library(estimatr)
library(modelsummary)
library(kableExtra)
library(webshot2)
library(patchwork)
library(cowplot)
library(plyr)
library(broom)
library(sf)
library(tmap)
library(tmaptools)
library(RColorBrewer)
library(htmlwidgets)
library(leaflet)
library(leafem)
library(DescTools)

conflicted::conflict_prefer_all("dplyr", quiet = TRUE)
conflicted::conflict_prefer_all("here", quiet = TRUE)
